
server:
  port: 8080

knife4j:
    enable: true
    openapi:
      title: aichat的api文档
#      description: "`我是测试`,**你知道吗**
#      # aaa"
#      email: xiaoymin@foxmail.com
#      concat: 八一菜刀
#      url: https://docs.xiaominfo.com
#      version: v4.0
#      license: Apache 2.0
#      license-url: https://stackoverflow.com/
#      terms-of-service-url: https://stackoverflow.com/
      group:
        default:
          group-name: ai脑经急转弯
          api-rule: package
          api-rule-resources:
            - com.jtyu.aichat.controller



ai:
  apiKey: 4ec76689-292b-4fad-b385-85f1c577490f